### ISSUE TITLE
Any chance for commonJS?

### ISSUE THREAD

**Issue by caspahouzer** [manumaticx/pagingcontrol#10]
Do we have a chance to use this widget without alloy?
I actually have a project where exactly this functionality is wanted, but I do not use alloy in this project.

That would be absolutely awesome!

**Comment by manumaticx** [comment]
Hm, actually it shouldn't be very difficult to port it to commonJs. I'll put it on my list but I'm busy with other stuff at the moment.

**Comment by caspahouzer** [comment]
thanks in advance!

- Sebastian

**Comment by deckameron** [comment]
Thank would be awesome, @manumaticx!

**Comment by deckameron** [comment]
@caspahouzer @manumaticx 

I have created a commonjs version of the pagingControl. I am still working on it to make improvements but it is pretty usable. Hope you find any use for it.

https://github.com/deckameron/TiPagingControl

**Comment by caspahouzer** [comment]
Awesome! Many thanks to you

- Sebastian 

Sent from my iPhone

**Comment by manumaticx** [comment]
Very nice! I appreciate your work @deckameron :)
good job, thanks a lot!

**Comment by deckameron** [comment]
Thank you, @caspahouzer @manumaticx!
I will keep working on it. If you guys have any suggestions, please let me know. :-)

**Comment by manumaticx** [comment]
Closing this issue. Again, lots of thanks to you, @deckameron :+1:
