### ISSUE TITLE
no any tabs displayed after init with tabs

### ISSUE THREAD

**Issue by falkolab** [manumaticx/pagingcontrol#11]
In widget.js you use code:
$.scrollableView.getViews() 
it get empty list but
$.scrollableView.children
return not empty list

Do you run your example from readme?

**Comment by manumaticx** [comment]
Did you call `setScrollableView()` ?

**Comment by falkolab** [comment]
Yes. Now I replace $.scrollableView.getViews()  to $.scrollableView.children and it work.

**Comment by manumaticx** [comment]
The "scrollable" Views within a scrollable View are not Child Views as they are added with `addView()` or `setViews` resulting in an Array of Ti.UI.Views as the `views` property (= `getViews()`) of the scrollableView. The `scrollableView.children` property returns the Views that were added with `scrollableView.add()`. So this example code should work when used like shown - only with scrollableView - not scrollView! ;)

**Comment by falkolab** [comment]
Ups ... urgently needs to sleep...
