### ISSUE TITLE
Nested scrollable tabs

### ISSUE THREAD

**Issue by pakoArtal** [manumaticx/pagingcontrol#13]
Hi Manuel, 

Thank you for sharing your code :-) 

I'm trying to nest two scrollable tabs but the inner scrollable tabs affect the main scrollable tabs.

I thought it was something related to event bubbling so I tried without luck to cancel it  with e.cancelBubble = true; on 'scroll', "click" and "select".

I have prepared an example to run:

https://github.com/pakoArtal/de.manumaticx.pagingcontrol_twoLevelPagingControlDemo

In your widget I added some "e.cancelBubble = true;" trying to make it work...

**Comment by manumaticx** [comment]
Hi @pakoArtal 

This is a simple design problem. Nesting scrollViews is always a pain and you should try to avoid that if possible.

Do you want only the inner tabs to be scrollable? Then you could simply use a tabgroup for the main tabs (but even this would be a confusing UX. But perhaps this is the easiest solution to get it working).

I'd suggest you go for another navigation approach. Either you could make the inner tabs not scrollable. Or you do not nest tabs in general and use another top-level navigation. Maybe a [drawer](https://github.com/manumaticx/Ti.DrawerLayout-Demo-Alloy-App)?

**Comment by pakoArtal** [comment]
Hi @manumaticx,
Thank you for your suggestions. I agree with you it's a confusing UX but it's a client requirement: both levels must be scrollable and be present all the time at the top of the App.

For my project I sort of solved it with an additional check in the 'onScroll' function from widget.js . Please note It's not a valid general solution. You can check it in my demo: https://github.com/pakoArtal/de.manumaticx.pagingcontrol_twoLevelPagingControlDemo.

**Comment by manumaticx** [comment]
Ah okay. Very cool. This works fine, well done!

I'll integrate this into the widget. Restricting the onScroll to the $.scrollableView is a general solution.

**Comment by manumaticx** [comment]
@pakoArtal Thank you!

**Comment by manumaticx** [comment]
@pakoArtal Is this issue solved now?

**Comment by pakoArtal** [comment]
It's working now.
Thank you @manumaticx
