### ISSUE TITLE
Tab color? 

### ISSUE THREAD

**Issue by santoshachari** [manumaticx/pagingcontrol#17]
Hi @manumaticx ,

Thanks for this widget!

Is there way I can change the color of the tabs?

**Comment by manumaticx** [comment]
Not yet

**Comment by santoshachari** [comment]
Can I change them with Android Theme? There must be a way - right?

**Comment by manumaticx** [comment]
Thanks to @ricardoalcocer this can now be set with `backgroundColor ` :+1:
