### ISSUE TITLE
Orientation change messes up tabs

### ISSUE THREAD

**Issue by ricardoalcocer** [manumaticx/pagingcontrol#19]
See this GIF, which also demonstrates the tableview reset I talked to you about.

![](http://sht.tl/L00lOx)

**Comment by manumaticx** [comment]
@ricardoalcocer I forked the conference app to reproduce this. I could fix the orientation bug. And I see what you mean with the tableview behavior. But this does also happen without the pagingcontrol widget. So this one is a Titanium issue. Btw: I've tested this with a ScrollView before, it works then. Seems this only happens with TableViews within ScrollableViews
