### ISSUE TITLE
New Event

### ISSUE THREAD

**Issue by ikaroraul** [manumaticx/pagingcontrol#22]
Hola que tal, muchas gracias por compartir tu código. Tengo una duda, el EVENTO "SELECT" solo funciona cuando se hace CLICK en el TAB, mi pregunta es como haría para aumentar un evento que me muestre cuando se cambie de VISTA a VISTA.

Gracias.

**Comment by manumaticx** [comment]
Can you explain this in english, please? Thanks

**Comment by manumaticx** [comment]
`select` event was added in 0.4.0 - closing this. feel free to reopen, if you're facing any problem!
