### ISSUE TITLE
Not Working with Drawer Menu

### ISSUE THREAD

**Issue by nazrdogan** [manumaticx/pagingcontrol#25]
its not working Drawer menu ( I use your module https://github.com/manumaticx/Ti.DrawerLayout) and Fokke's widget

    <Alloy>
	<Widget id="drawer" src="nl.fokkezb.drawer">

		<Window module="xp.ui" role="leftWindow">
			<Label color="red">I am left</Label>
		</Window>
		<NavigationWindow platform="ios" role="centerWindow">
			<Window>
				<LeftNavButton>
					<Button onClick="toggle">Left</Button>
				</LeftNavButton>
				<Label>I am</Label>
				<RightNavButton>
					<Button onClick="toggle">Right</Button>
				</RightNavButton>
			</Window>
		</NavigationWindow>
		<View platform="android" role="centerWindow">
			<Widget id="paging" src="de.manumaticx.pagingcontrol" onSelect="tabHandler" />
			<ScrollableView id="scrollableView">
				<View title="Yellow" backgroundColor="yellow" />
				<View title="Orange" backgroundColor="orange" />
				<View title="Red" backgroundColor="red" />
				<View title="Purple" backgroundColor="purple" />
				<View title="Blue" backgroundColor="blue" />
			</ScrollableView>
		</View>
		<Window module="xp.ui" role="rightWindow">
			<Label>I am right</Label>
		</Window>

	</Widget>
</Alloy>

 index.js 

       $.drawer.open();
          function toggle(e) {
          var fn = 'toggle' + e.source.title + 'Window';
         $.drawer[fn]();
        }
       function tabHandler(e) {
        console.log('selected tab ', e.tab);
         }
       $.paging.setScrollableView($.scrollableView);

**Comment by konstantinbueschel** [comment]
Hi,

you need to set layout="vertical" for your centerWindow view and for the paging view top=0, otherwise the scrollable view will overlay the paging view.

**Comment by manumaticx** [comment]
@nazrdogan Did @konstantinbueschel help you? Can I close this?

**Comment by nazrdogan** [comment]
yeah :) sorrry for delay . I forget  .you can close
