### ISSUE TITLE
Reinitiate/Refresh/Dynamic creation?

### ISSUE THREAD

**Issue by ananth-kumar** [manumaticx/pagingcontrol#26]
How do i dynamically create views in same window?

**Comment by manumaticx** [comment]
Hi, sorry for the (veeery) late reply!

I've added a `refresh` method in 0.4.5

According to the example in the readme, this was the code for testing it:

```js
function addView(e){
  $.scrollableView.addView(Ti.UI.createView({
    title: "Green",
    backgroundColor: 'green'
  }));
  
  $.paging.refresh();
};
```

**Comment by ananth-kumar** [comment]
Thank you very much 👍
