### ISSUE TITLE
Last tab Android

### ISSUE THREAD

**Issue by annamf** [manumaticx/pagingcontrol#29]
Hi, 
 On Android, the last Tab title doesn't appear. The others ok but the last no. You can scroll the views and the las tab being active but without title. And the last tab click event doesn't work too.

this happen with your example. The blue tab doesn't have title and you can't click over to change to this tab. The Purple tab is the last you can see.

Please help me.

**Comment by manumaticx** [comment]
hi @annamf 

I'm not able to reproduce this. If I try the exact example code from the readme, it works just fine.

Can you provide some more info about your setup. Maybe there's a conflict elsewhere in the code.

**Comment by annamf** [comment]
Is the same code that in example code from the readme. I was testing the example in a new project. So my files are the same that in your example.

On android 4.2 and android 5.

Ti.SDK 5.1.2.GA

**Comment by manumaticx** [comment]
Okay, I tested again with 5.1.2.GA on Android 4.3.1 emulator but it works fine too. Can you [send me](mailto:manumaticx@gmail.com) your project?

**Comment by annamf** [comment]
The problem is on Android 4.4.2. Ok I'm going to send you my project.

**Comment by manumaticx** [comment]
The Android version is not the problem. It must be something else

**Comment by annamf** [comment]
I've just sent you my project. The same project on android 5 works fine. I'm trying to see what's happening too but all seems correct.... all the tabs ara added and the titles are correct.... but the last title isn't showed....

**Comment by manumaticx** [comment]
I've also tested 4.4.2 - I cannot reproduce! (didn't got your mail yet)

**Comment by annamf** [comment]
See on junk email, this is [my mail account](amurcia.dev@gmail.com)

I'm testing on a Samsung Galaxy core 2

**Comment by manumaticx** [comment]
got it, thx

**Comment by manumaticx** [comment]
Still not able to reproduce this. I've setup a new 4.4.2 AVD with MDPI screen (as the galaxy core 2) but the project you've send me works as expected. Sorry.
